
sudo: required
language: bash

services:
  - docker

script:
  - ./.build/build.sh --app_name=mailpile --app_version=1.0.0rc2 --app_distribution=alpine-3.5 --docker_repository=glego --docker_no_cache --docker_push